openapi: 3.0.0
servers:
  - description: SwaggerHub API
    url: HTTP
  - description: SwaggerHub Secure API
    url: HTTPS
info:
  title: A simple E-commerce API
  description: A simple API for managing products, orders, users, and categories in an e-commerce system.
  version: 1.0.0
tags:
  - name: product
    description: Everything about product
  - name: user
    description: Operations about user
  - name: order
    description: Information about order
paths:
  /products:
    get:
      tags:
        - product
      summary: get all products
      description: get all available products.
      responses:
        '200':
          description: get all products successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'

    post:
      tags:
        - product
      summary: create a new product
      description: create a new product
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        '201':
          description: create new product successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'

  /products/{productId}:
    get:
      tags:
        - product
      summary: get a product
      description: get a product
      parameters:
        - name: productId
          required: true
          in: path
          description: id of the product
          schema:
            type: string
      responses:
        '200':
          description: get a product successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '404':
          description: Product not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    put:
      tags:
        - product
      summary: update a product
      description: update a product by the product id
      parameters:
        - name: productId
          required: true
          in: path
          description: id of the product
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        '200':
          description: the product with that product id is updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'

    delete:
      tags:
        - product
      summary: delete the product by the product id
      description: delete the product by the product id
      parameters:
        - name: productId
          required: true
          in: path
          description: id of the product
          schema:
            type: string
      responses:
        '204':
          description: the product with that product id is deleted successfully

  /users:
    post:
      tags:
        - user
      summary: create a new user
      description: create a new user
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '201':
          description: create new user successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'

  /users/{userId}:
    get:
      tags:
        - user
      summary: get a user
      description: get a user
      parameters:
        - name: userId
          required: true
          in: path
          description: id of the user
          schema:
            type: string
      responses:
        '200':
          description: get a user successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '404':
          description: User not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    put:
      tags:
        - user
      summary: update a user
      description: update a user by the user id
      parameters:
        - name: userId
          required: true
          in: path
          description: id of the user
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '200':
          description: the user with that user id is updated successfully
        '404':
          description: User not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /orders:
    get:
      tags:
        - order
      summary: get all orders
      description: get all available orders.
      responses:
        '200':
          description: get all orders successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'

    post:
      tags:
        - order
      summary: create a new order
      description: create a new order
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Order'
      responses:
        '201':
          description: create new order successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'

  /orders/{orderId}:
    get:
      tags:
        - order
      summary: get an order
      description: get an order
      parameters:
        - name: orderId
          required: true
          in: path
          description: id of the order
          schema:
            type: string
      responses:
        '200':
          description: get an order successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
        '404':
          description: Order not found!
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    put:
      tags:
        - order
      summary: update an order
      description: update an order by the order id
      parameters:
        - name: orderId
          required: true
          in: path
          description: id of the order
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '200':
          description: the user with that user id is updated successfully
        '404':
          description: User not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      
    delete:
      tags:
        - order
      summary: delete the order by the order id
      description: delete the order by the order id
      parameters:
        - name: orderId
          required: true
          in: path
          description: id of the order
          schema:
            type: string
      responses:
        '204':
          description: the order with that order id is deleted successfully

components:
  schemas:
    Product:
      type: object
      properties:
        productId:
          type: string
          example: '102'
        title:
          type: string
          example: 'product1'
        price:
          type: number
          example: 1
        description:
          type: string
          example: 'this is a product'
        size:
          type: number
          example: '40'
        images:
          type: string
          example: 'https://fastly.picsum.photos/id/5/640/480.jpg'
        categoryId:
          type: string

    User:
      type: object
      properties:
        userId:
          type: string
          example: '203'
        email:
          type: string
          example: 'user@mail.com'
        password:
          type: string
          example: 'password'
        fullname:
          type: string
          example: 'John Smith'
        role:
          type: string
          example: 'customer'
        avatar:
          type: string
          example: 'https://fastly.picsum.photos/id/5/640/480.jpg'
    
    Order:
      type: object
      properties:
        orderId:
          type: string
          example: '304'
        userId:
          type: string
          example: '203'
        products:
          type: array
          example: 'user@mail.com'
        totalPrice:
          type: number
          example: 1024
        createAt:
          type: string
          example: '14/03/2024'

    Error:
      type: object
      properties:
        message:
          type: string
          description: error message!